### ISSUE TITLE
Lässt sich nicht in der Loupedeck Software installieren

### ISSUE THREAD

**Issue by TMA84** [ulfwuestefeld/MicrosoftTeamsPlugin#1]
Hi,

ich bekomme bei der Installation folgende Meldung:

Library package has failed to install

und
Leider konnte das Add-On nicht installiert werden

Kannst du kurz erklären wie die Installation funktioniert?

Viele Grüße
Tobias

**Comment by ulfwuestefeld** [comment]
[MicrosoftTeams.zip](https://github.com/ulfwuestefeld/MicrosoftTeamsPlugin/files/10580985/MicrosoftTeams.zip)

Beende mal Loupedeck (im Systray, "Loupedeck anhalten") und entpack die .zip mal in %LOCALAPPDATA%\Loupedeck\Plugins\, dann sollte es in Loupedeck - nach dem Start von Loupedeck - auftauchen.

**Comment by TMA84** [comment]
Das scheint auch nicht zu funktionieren, hier bekomme ich jetzt aber einen anderen Fehler:
_One or more plugins were not loaded
The following plugins were not loaded because they had malfunctioned: Microsoft Teams_

**Comment by ulfwuestefeld** [comment]
Kannst du bitte einmal nachsehen, was in den Dateien %LOCALAPPDATA%\Loupedeck\Logs\plugin_logs\MicrosoftTeams.log und unter %LOCALAPPDATA%\Loupedeck\Logs\ sowie  %LOCALAPPDATA%\Loupedeck\Logs\ws_lst in den Logs bei deinem Installationsversuch steht.

**Comment by ulfwuestefeld** [comment]
Ich habe gerade ein "Release" mit einer Loupedeck-Plugin-Datei erstellt. Diese sollte sich ordentlich installieren lassen.[https://github.com/ulfwuestefeld/MicrosoftTeamsPlugin/releases/download/v0.1/MicrosoftTeamsPlugin.lplug4](url)

**Comment by TMA84** [comment]
Danke das Release lässt sich wunderbar installieren und verwenden. Danke für die Hilfestellung.
Super Plugin für Teams
